### PR TITLE
feat: Added Module Feature Table automation

### PR DESCRIPTION
**Pull request by AlexanderSehr**
# Overview/Summary

- Added generated (res) modules feature table
  - Replicating the same logic we had in CARML - slightly altered to the public registries' needs 
- Re-used workflow logic of apiSpecs update (i.e. but with a daily update)
- This generates
  - A markdown with the module status badges (both res + ptn) 
  -  A CSV with module features (only res)
- Disabled Linter for 2 files that are used by utilities

> **NOTE:** I had to implement exceptions like `    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPositionalParameters', '', Justification='For Join-Path it''s very difficult to read the cmdlet without positional parameters.')]` to get around Linter. I'd highly recommend to somehow configure the checker - or disable it if needed.

image

Linter Regex check:
image

### CODE REVIEW

**Comment by matebarabas** [comment]
@AlexanderSehr, this is an awesome feature, thank you for porting it over from CARML!

If possible, I'd like to have a chat with you before this gets merged. I have the following thoughts:
- I wouldn't put it on a separate page under the Bicep Resource Modules, not only because the navigation menu is getting too crowded already, but also because it raises questions like "why isn't this same sub-menu available under all the other indexes?". 
- I think it would be easier to explore this content if it was part of the same index page - the same tables we already have, to be precise.
- I'd recommend a 2-step approach: 
  1) make this table part of the Bicep Resource index page as a separate collapsable box
  2) converge this information into the list of [Available Modules](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/#available-modules).

I'm sure there are technical considerations behind your design that I'm not aware of - e.g., you put this table in a separate file because it's easier to re-generate the whole file, etc. Let's catch up next week on this!

**Comment by AlexanderSehr** [comment]
Hey @matebarabas, 
yes it is easier, but we have actually already a solution to embedd the table in an existing markdown page.

The reason is indeed a different & deliberate one, and the same why we moved the badges from the front page in CARML to a wiki page. 
Case and point: Each pipeline badge is a API call. And if you have enough of them or refresh the page often enough, you're eventually blocked by GitHub and cannot use it for some time. In CARML, this move solved it for us - and was actually not too bad, as it was mostly for us maintainers to see if there is an issue somewhere.

Before the move, sometime early this year people started having random issues to get to any GitHub page after visiting ours. So, yeah... 

Happy to discuss, but you can imagine what my recommendation will be 😄
cc: @eriqua

**Comment by AlexanderSehr** [comment]
One more thing actually - I don't think it would make much sense to have the same table (with features) for patterns, as there is no such spec. And for TF it is... a bit more challenging, given that we'd need to find and scan an increasingly big number of repositories to get to the same output. Not to mention that it's not that easy to understand in which file you'd even find the input variables as TF doesn't care much. The only reasonable way to do this would be to only download the variables.tf from each repo in the modules table and search in it - having a requirement that all variables are in there (which we might have).

**Comment by eriqua** [comment]
Confirming what Alex mentioned. A couple of thoughts on top of that. 

Ideally, the status badge page should be internal to the core team and module owners. There's no real benefit in showing it to the public. 

However, users would find beneficial to have an overview of features/extention resources provided by each resource module.

What about splitting badges and module features? Not necessarily now, but as a planned next step. We could discuss converging features info into available modules as Mate suggested, but keeping the badge list separated and, possibly, internal only.

**Comment by AlexanderSehr** [comment]
> Confirming what Alex mentioned. A couple of thoughts on top of that.
> 
> Ideally, the status badge page should be internal to the core team and module owners. There's no real benefit in showing it to the public.
> 
> However, users would find beneficial to have an overview of features/extention resources provided by each resource module.
> 
> What about splitting badges and module features? Not necessarily now, but as a planned next step. We could discuss converging features info into available modules as Mate suggested, but keeping the badge list separated and, possibly, internal only.

Good idea @eriqua, we could do that too (the split). 
I might argue though that the features overview is more interesting to us maintainers to see if any module is missing a feature and reach out to the owner. I would assume a consumer would rather find a module in the Public Registry and look at its features than to navigate to yet another website (this one) to see what features it has. However, it wouldn't hurt either as long as this site scales well into the width. I can only assume the width issue is the reason the module index pages are close to the only ones explicitely without the navigation bar to the left (right, @matebarabas?).

I also wonder (but can't really say) how this feature table could even be combined with the module index markdown as that's generated via Go, isn't it?

In any case if we don't want to go ahead with the proposed structure as let's say MVP 1.0, I'd advocate to simply remove the features from the table in the PR. Our main concern should be to get this badge overview which is currently entirely missing, making it hard so keep track of any modules with 'issues'. 
If also displaying the features next to it currently raises more issues than it helps (at this location), I'd rather have it removed. The reason it's only there in the first place is because I had the logic already (almost) ready :D

**Review by matebarabas — APPROVED** [review]
Judging based on the resulted CSV/MD files, it all looks good to me!

**Pull request merged**
