### PR TITLE
Suggested spec change to resource locks (`lock`) interface for Terraform

### PR DESCRIPTION
**Pull request by MariusStorhaug**
# Overview/Summary

## This PR fixes/adds/changes/removes

- Updates the suggestion for the terraform interface `lock`
- Fixes: #423

### Breaking Changes

N/A

## As part of this Pull Request I have

- [x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Verified-Modules/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Verified-Modules/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Verified-Modules/)
- [x] Ensured PR tests are passing
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by MariusStorhaug — COMMENTED** [review]
comment removed

**Comment by matt-FFFFFF** [comment]
I haven't tested this, please don't merge until I have done so

**Comment by matt-FFFFFF** [comment]
Thanks for the PR!

**Comment by MariusStorhaug** [comment]
Done with initial changes.

**Comment by matt-FFFFFF** [comment]
After consideration, this makes the module code more fragile, as you have to check for the object being null, and then the members of the object as well. I think the more robust solution is to stick to using optional & have nullable=false.

**Pull request closed without merging**
