### PR TITLE
feat: [feat/doc-updates] open external links in new tab/window

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

> This is a PR not for the main branch

External links will be opened in a new tab instead of navigating away from the current page.

## This PR fixes/adds/changes/removes

none

### Breaking Changes

none

## As part of this Pull Request I have

- [x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Verified-Modules/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Verified-Modules/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Verified-Modules/)
- [x] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ReneHezser** [comment]
@matebarabas the first PR for the doc update branch

**Comment by AlexanderSehr** [comment]
Hey @ReneHezser,
would that then be the case for literally all links? I'd usually use my mousewheel if I want to open somthing in a new tab and otherwise would always want to navigate to a given page. Not saying we cannot change it - but if this works like I think it will, then we're essentially limiting the user 😄

**Comment by ReneHezser** [comment]
> Asking for a friend

Hey @AlexanderSehr
I understand the concerns your friend has. The web is divided if it is best to open external links (pointing to another domain) should be opened in a new tab/window, or not. In our case, I would like to do so, as they provide additional information to read, but would navigate away from the "follow me guide" on the site.

**Comment by matebarabas** [comment]
A few comments/thoughts:
- I think opening **external** links in a new tab is common best practice, so I think we should adapt this practice.
- We need to test/make sure that this solution really only gets triggered in case of external links (i.e., stuff outside of the AVM website, including any of the GH repos, etc.)
- We need to test/make sure that this gets triggered in case of http and https links.
- This PR is not for main, but for a long-standing documentation branch, we'll collaborate on and release to main when we're ready for the first wave of changes.

**Pull request merged**
